# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: ranking_dev
  timeout: 5000
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: ranking_test
  timeout: 5000
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: ranking_pro
  timeout: 5000
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock


